dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t travis-ci-build-stages-demo .
      - docker images
      - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/travis-ci-build-stages-demo
      - docker push $DOCKER_USERNAME/travis-ci-build-stages-demo
    - stage: db
      script: docker run --name my-postgres -e POSTGRES_PASSWORD=secret -p 5433:5432 -d postgres
    - stage: backend
      script: docker run --rm -p 8080:8080 $DOCKER_USERNAME/travis-ci-build-stages-demo
    #- script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt